services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: hghuy/localapi:v1
    container_name: webapi
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my_network
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - '1433:1433' # Remove if external access is not needed
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Giahuy@1565'
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - my_network

networks:
  my_network:

volumes:
  sqlvolume:
